### PR TITLE
BJEJ-13 animation of result page

### PR DESCRIPTION
**Pull request by LarryMatte**
resultanimation

### CODE REVIEW

**Comment by jasonlemay** [comment]
J'AI GAGNÉ!

**Comment by christiangoudreau** [comment]
KLOL

**Comment by LarryMatte** [comment]
@jasonlemay yep, you won the GRAND PRIZE to be the first one to review this PR ;)

**Comment by olafleur** [comment]
Yé! Je vote pour @jasonlemay aussi!

**Comment by LarryMatte** [comment]
What about a little review guys ;) ?

**Comment by christiangoudreau** [comment]
LGTM

**Pull request merged**
